services:
  api:
    container_name: day-57-api
    image: node:22.9.0
    working_dir: /app/api
    volumes:
      - './api:/app/api'
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: ['npm','run','start:dev']

  db:
    container_name: day-57-db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5006:5432'

