services:
  api:
    container_name: day-54-api
    image: node:22.9.0
    working_dir: /app/api
    volumes:
      - './api:/app/api'
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: ['npm','run','start:dev']

  db:
    container_name: day-54-db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    ports:
      - '5002:5432'
    volumes:
      - './db:/var/lib/postgresql/data'
